AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  carisdataapi

#s3 bucket
Parameters:
  S3BucketName:
    Type: String
    Description: S3 Bucket Name
    Default: carisdataapi
Resources:
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: carisdataapi
      Handler: app.main_handler
      Runtime: python3.8
      CodeUri: .
      Timeout: 30
      MemorySize: 256
      Events:
        ApiGatewayEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY


