AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  dataapi

Resources:
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: dataapi
      Handler: app.main_handler
      Runtime: python3.8
      CodeUri: .
      Timeout: 30
      MemorySize: 256
      Events:
        ApiGatewayEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY


