positif_info = {
    "_id": 0,
    "case_id": 1,
    "date_modified": 1,
    "properties.schooling_year": 1,
    "properties.school_commune_1": 1,
    "properties.patient_code": 1,
    "properties.infant_commune": 1,
    "properties.gender": 1,
    "properties.infant_dob": 1,
    "properties.dat_peyman_fet": 1,
    "properties.eskew_peye": 1,
    "properties.age": 1,
    "sexe": 1,
    "category": 1,
    "quarter": 1,
    "properties.case_type": 1,
    "closed": 1,
}

oev_info = {
    "_id": 0,
    "case_id": 1,
    "date_modified": 1,
    "properties.schooling_year": 1,
    "properties.school_commune_1": 1,
    "properties.patient_code": 1,
    "properties.infant_commune": 1,
    "properties.gender": 1,
    "properties.infant_dob": 1,
    "properties.dat_peyman_fet": 1,
    "properties.eskew_peye": 1,
    "properties.age": 1,
    "sexe": 1,
    "category": 1,
    "quarter": 1,
    "properties.case_type": 1,
    "properties.parent_patient_code": 1,
    "closed": 1,
}

siblings_info = {
    "_id": 0,
    "case_id": 1,
    "date_modified": 1,
    "properties.schooling_year": 1,
    "properties.school_commune": 1,
    "properties.patient_code": 1,
    "properties.infant_commune": 1,
    "properties.gender": 1,
    "properties.infant_dob": 1,
    "properties.dat_peyman_fet": 1,
    "properties.eskew_peye": 1,
    "properties.age": 1,
    "sexe": 1,
    "category": 1,
    "quarter": 1,
    "properties.case_type": 1,
    "properties.parent_patient_code": 1,
    "closed": 1,
}

cwv_info = {
    "_id": 0,
    "case_id": 1,
    "date_modified": 1,
    "properties.schooling_year": 1,
    "properties.school_commune_1": 1,
    "properties.gender_sex": 1,
    "properties.dob": 1,
    "properties.dat_peyman_fet": 1,
    "properties.eske_peye": 1,
    "age": 1,
    "sexe": 1,
    "category": 1,
    "quarter": 1,
    "properties.case_type": 1,
    "closed": 1,
}

dreams_info = {
    "_id": 0,
    "case_id": 1,
    "date_modified": 1,
    "properties.schooling_year": 1,
    "properties.dreams_code": 1,
    "properties.school_commune_1": 1,
    "properties.gender": 1,
    "properties.infant_dob": 1,
    "properties.dat_peyman_fet": 1,
    "properties.eske_peye": 1,
    "age": 1,
    "sexe": 1,
    "category": 1,
    "quarter": 1,
    "properties.case_type": 1,
    "closed": 1,
}
